export enum NotificationType {
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  FORM_APPROVED = 'FORM_APPROVED',
  FORM_REJECTED = 'FORM_REJECTED',
  SUMMARY_REQUIRED = 'SUMMARY_REQUIRED',
  SYSTEM = 'SYSTEM',
  PREVIOUS_DATA_CHECK = 'PREVIOUS_DATA_CHECK',
}